spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/robot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password:

logging:
  config: classpath:log/logback-spring.xml